ipc = on

preload = /home/trainingmontage/Pictures/CosmicCliffsWallpaper.png
preload = /home/trainingmontage/Pictures/PillarsOfCreationWallpaper.png 
preload = /home/trainingmontage/Pictures/TarantulaNebulaWallpaper.png

wallpaper = HDMI-1,/home/trainingmontage/Pictures/CosmicCliffsWallpaper.png
wallpaper = DP-1,/home/trainingmontage/Pictures/PillarsOfCreationWallpaper.png 
wallpaper = DP-2,/home/trainingmontage/Pictures/TarantulaNebulaWallpaper.png 
